### ISSUE TITLE
It's possible to put conflicting transactions in the transaction pool

### ISSUE THREAD

**Issue by LeeSmet** [nbh-digital/goldchain#36]
Though it seems they are not accepted in blocks

**Comment by LeeSmet** [comment]
Seems like the transactionpool no longer validates new transactions in the context of the entire already existing pool anymore

**Comment by LeeSmet** [comment]
Actually, regular transactions in the pool can still be chained, so this does still work. The question is, why does this work for sending coins, but are authorized addresses ignored

**Comment by GlenDC** [comment]
When you post a transaction to the `/transactionpool/transactions` endpoint it calls the TransactionPool's method `AcceptTransactionSet` with only that defined transaction:

https://github.com/threefoldtech/rivine/blob/47d7daa3ab9e07266ad8352a0ff71783bf98903a/pkg/api/transactionpool.go#L146-L149

This was already the case since at least 11 months ago, if not more.

It will call the Consensus module's `TryTransactionSet` using that same singleton:

https://github.com/threefoldtech/rivine/blob/47d7daa3ab9e07266ad8352a0ff71783bf98903a/modules/transactionpool/accept.go#L237-L242

This behaviour also hasn't changed.

This effectively means that transactions are always validated on their own, not within the context of the pool. Which makes me puzzled why the chaining of regular transactions work. A severe case of insomnia...

**Comment by GlenDC** [comment]
Yeah ok, I understand it once again. It boils down to the following.

As we know the transaction pool keeps a list of transaction lists (where the latter are called transaction set, such that you could say a list of transaction sets, even though it is in fact a set of transaction sets to be precise).

Each time you post a new transaction it adds it as a new transaction set.

The reason why spending unconfirmed coin outputs / block stake outputs work, is because it keeps track of a mapping called "known objects", this includes transaction IDs, block output (in/out) IDs and coin output (in/out) IDs.

Prior to trying the regular transaction on it self, it will collect also all identifiers related to all transactions in the current transaction set (the singleton of that one transaction). If any of these ids are found as known objects it will mark it as a conflict (which is what also happens in case you have spent an unconfirmed coin out). As soon as there is at least one conflict it will collect all related transactions as a single transaction set, ensuring the input transactions are put last. It will then instead of validating the transaction on its own, validate it instead as a whole, and thus allowing the spending of unconfirmed objects.

To come back to your original issue @LeeSmet. We can therefore conclude that the reason why you can double authorise an address within the same tx pool, is because this does not cause conflicts, given it is about something else than a simple ID, but for some arbitrary rules defined on all transactions, not known by the transaction pool.

**Comment by GlenDC** [comment]
I would suggest to remove the collection of transactions as separate sets and instead keep it as a single set. As long as the transactions stay in the order as accepted (meaning if a tx A that depends on another tx B, we should ensure that tx A comes after tx B in the list). Currently that would be guaranteed as we do not do any custom ordering. But should we ever want to order based on certain priorities, we do need to ensure this dependency order is respected at all times, as to still be able to create them as blocks.

But for now, it seems like a simple enough change.

**Comment by LeeSmet** [comment]
I agree, this is probably the best way forward (at least for now). Custom ordering is ever really needed in case there is a period where the amount of txes posted is greater than the amount of txes processed, though even then given that the block creators are controlled by us for the majority, that is not really ever going to be a problem I think

**Comment by GlenDC** [comment]
I proposed it as a change in Rivine, I would suggest to discuss further there if it is related to these findings and the resulting proposal: https://github.com/threefoldtech/rivine/issues/563
